axyz/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path('create/recamara/', views.CreateRecamara.as_view(), name="create_recamara"),
    path('list/recamara/', views.ListRecamara.as_view(), name="list_recamara"),
    path('detail/recamara/<int:pk>/', views.DetailRecamara.as_view(), name="detail_recamara"),
    path('update/recamara/<int:pk>/', views.UpdateRecamara.as_view(), name="update_recamara"),
    path('delete/recamara/<int:pk>/', views.DeleteRecamara.as_view(), name="delete_recamara"),

    path('create/bano/', views.CreateBano.as_view(), name="create_bano"),
    path('list/bano/', views.ListBano.as_view(), name="list_bano"),
    path('detail/bano/<int:pk>/', views.DetailBano.as_view(), name="detail_bano"),
    path('update/bano/<int:pk>/', views.UpdateBano.as_view(), name="update_bano"),
    path('delete/bano/<int:pk>/', views.DeleteBano.as_view(), name="delete_bano"),

    path('create/cocina/', views.CreateCocina.as_view(), name="create_cocina"),
    path('list/cocina/', views.ListCocina.as_view(), name="list_cocina"),
    path('detail/cocina/<int:pk>/', views.DetailCocina.as_view(), name="detail_cocina"),
    path('update/cocina/<int:pk>/', views.UpdateCocina.as_view(), name="update_cocina"),
    path('delete/cocina/<int:pk>/', views.DeleteCocina.as_view(), name="delete_cocina"),

    path('create/comedor/', views.CreateComedor.as_view(), name="create_comedor"),
    path('list/comedor/', views.ListComedor.as_view(), name="list_comedor"),
    path('detail/comedor/<int:pk>/', views.DetailComedor.as_view(), name="detail_comedor"),
    path('update/comedor/<int:pk>/', views.UpdateComedor.as_view(), name="update_comedor"),
    path('delete/comedor/<int:pk>/', views.DeleteComedor.as_view(), name="delete_comedor"),

    path('create/sala/', views.CreateSala.as_view(), name="create_sala"),
    path('list/sala/', views.ListSala.as_view(), name="list_sala"),
    path('detail/sala/<int:pk>/', views.DetailSala.as_view(), name="detail_sala"),
    path('update/sala/<int:pk>/', views.UpdateSala.as_view(), name="update_sala"),
    path('delete/sala/<int:pk>/', views.DeleteSala.as_view(), name="delete_sala"),

    path('create/oficina/', views.CreateOficina.as_view(), name="create_oficina"),
    path('list/oficina/', views.ListOficina.as_view(), name="list_oficina"),
    path('detail/oficina/<int:pk>/', views.DetailOficina.as_view(), name="detail_oficina"),
    path('update/oficina/<int:pk>/', views.UpdateOficina.as_view(), name="update_oficina"),
    path('delete/oficina/<int:pk>/', views.DeleteOficina.as_view(), name="delete_oficina"),
]

home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Inicio.as_view(), name="inicio"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    
    path('detail/profile/<int:pk>/', views.DetailProfile.as_view(), name="detail_profile"),
    path('update/profile/<int:pk>/', views.UpdateProfile.as_view(), name="update_profile"),

    path('ubicacion/', views.Ubicacion.as_view(), name="ubicacion"),
    path('nosotros/', views.Nosotros.as_view(), name="nosotros"),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
</head>
<body class="main-content-per" style="background-color: #fffde7; margin: 0; padding: 0;">
  <nav class="navbar navbar-expand-lg" data-bs-theme="light" style="background-color: #443068; padding-bottom: 5px; padding-top: 5px;">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home:inicio' %}" style="padding-right: 30px; padding-left: 25px; padding-bottom: 0;">
            <img src="/static/images/logos/Logo.png" alt="Logo Axolotl Furniture" width="150px">
          </a>
          <button class="navbar-toggler" type="button"  style="background-color: #aacb4e; border-radius: 10px;" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          {% if request.user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link active" style="color: white; font-size: 24px;" href="{% url 'home:inicio' %}">Inicio</a>
              </li>
<!-- ----------------------------------------------------------------------------------------- -->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" style="color: white; font-size: 24px;" role="button" aria-haspopup="true" aria-expanded="false">
                    Categorías
                </a>
                <div class="dropdown-menu" style="border-radius: 10px;">
                  <a class="dropdown-item" href="{% url 'core:list_recamara' %}">Recamaras</a>
                  <a class="dropdown-item" href="{% url 'core:list_bano' %}">Baños</a>
                  <a class="dropdown-item" href="{% url 'core:list_cocina' %}">Cocinas</a>
                  <a class="dropdown-item" href="{% url 'core:list_comedor' %}">Comedores</a>
                  <a class="dropdown-item" href="{% url 'core:list_sala' %}">Salas</a>
                  <a class="dropdown-item" href="{% url 'core:list_oficina' %}">Oficinas</a>
                </div>
              </li>
<!-- --------------------------------------- MOFICICAR -------------------------------------------------- -->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" style="color: white; font-size: 24px;" role="button" aria-haspopup="true" aria-expanded="false">
                    Servicios
                </a>
                <div class="dropdown-menu" style="border-radius: 10px;">
                  <a class="dropdown-item" href="https://axolotlfurniture.blogspot.com/">Asesorías</a>
                </div>
              </li>
<!-- ------------------------------------------ SECCION A MODIFICAR DETALLES ----------------------------------------------- -->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:ubicacion' %}" style="color: white; font-size: 24px;"> Ubicación </a>
              </li>
<!----------------------------------------------------IMPLEMENTAR HTML------------------------------------------------------------>
              <li class="nav-item ">
                <a class="nav-link" href="{% url 'home:nosotros' %}" style="color: white; font-size: 24px;"> Nosotros </a>
              </li>
            </ul>
<!------------------------------------------------------------------------------------------------------------------------->
            <form class="d-flex" role="search">
                <input class="form-control  me-sm-2" type="search" placeholder="Buscar..."  style="border-radius: 10px;">
                <button type="button" class="btn" style="border-radius: 10px; background-color: #aacb4e;">
                  <img src="/static/images/iconos/lupa.png" alt="lupa" width="30px">
                </button>
            </form>
<!------------------------------------------ USUARIO ------------------------------------------>
            <div class="dropdown">
              <button class="btn" data-bs-toggle="dropdown" aria-expanded="false" style="border-radius: 10px; background-color: transparent; padding-left: 50px;">
                <img src="/static/images/iconos/usuario.png" alt="lupa" width="35px">
              </button>
              <ul class="dropdown-menu dropdown-menu-lg-end text-center">
                <h1> {{ user }} </h1>
                  <br>
                <a href="{% url 'home:logout' %}" class="btn btn-outline-danger" style="border-radius: 10px;">LogOut</a>
              </ul>
            </div>
          </div>
    {% endif %}
        </div>
      </nav>
<!------------------------------------------------------- CONTENIDO ------------------------------------------------------->
        {% block content %} {% endblock content %}
<!-------------------------------------------------------------MODIFICAR FOOTER------------------------------------------------------------>
  <br><br>
  {% if request.user.is_authenticated %}
        <footer style="background-color: #443068; padding-bottom: 40px; padding-top: 15px;">
          <div class="container text-center">
            <div class="row align-items-center">
              <!-- columana 1 -->
              <div class="col">
                <br>
                <img class="imagen-size" src="/static/images/logos/LogoV3.png" alt="Logo Axolotl Furniture" width="350px">
              </div>
              <!-- columna 2 -->
              <div class="col">
                <p class="h5 text-center" style="color: white;">Siguenos en nuestras redes sociales</p>
              <br>
                <div class="container text-center">
                  <div class="row align-items-center">
                      <div class="col">
                          <a href="https://www.facebook.com/profile.php?id=61551399500090&mibextid=ZbWKwL">
                              <img src="/static/images/iconos/facebook.png" alt="facebook" width="80px">
                          </a>
                      </div>
                      <div class="col">
                          <a href="https://instagram.com/axyz.furniture?igshid=OGQ5ZDc2ODk2ZA==">
                              <img src="/static/images/iconos/instagram.png" alt="instagram" width="80px">
                          </a>
                      </div>
                  </div>
              </div>
            </div>
            </div>
          </div>
        </footer>
        {% endif %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>