axyz/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path('create/recamara/', views.CreateRecamara.as_view(), name="create_recamara"),
    path('list/recamara/', views.ListRecamara.as_view(), name="list_recamara"),
    path('detail/recamara/<int:pk>/', views.DetailRecamara.as_view(), name="detail_recamara"),
    path('update/recamara/<int:pk>/', views.UpdateRecamara.as_view(), name="update_recamara"),
    path('delete/recamara/<int:pk>/', views.DeleteRecamara.as_view(), name="delete_recamara"),

    path('create/bano/', views.CreateBano.as_view(), name="create_bano"),
    path('list/bano/', views.ListBano.as_view(), name="list_bano"),
    path('detail/bano/<int:pk>/', views.DetailBano.as_view(), name="detail_bano"),
    path('update/bano/<int:pk>/', views.UpdateBano.as_view(), name="update_bano"),
    path('delete/bano/<int:pk>/', views.DeleteBano.as_view(), name="delete_bano"),

    path('create/cocina/', views.CreateCocina.as_view(), name="create_cocina"),
    path('list/cocina/', views.ListCocina.as_view(), name="list_cocina"),
    path('detail/cocina/<int:pk>/', views.DetailCocina.as_view(), name="detail_cocina"),
    path('update/cocina/<int:pk>/', views.UpdateCocina.as_view(), name="update_cocina"),
    path('delete/cocina/<int:pk>/', views.DeleteCocina.as_view(), name="delete_cocina"),

    path('create/comedor/', views.CreateComedor.as_view(), name="create_comedor"),
    path('list/comedor/', views.ListComedor.as_view(), name="list_comedor"),
    path('detail/comedor/<int:pk>/', views.DetailComedor.as_view(), name="detail_comedor"),
    path('update/comedor/<int:pk>/', views.UpdateComedor.as_view(), name="update_comedor"),
    path('delete/comedor/<int:pk>/', views.DeleteComedor.as_view(), name="delete_comedor"),

    path('create/sala/', views.CreateSala.as_view(), name="create_sala"),
    path('list/sala/', views.ListSala.as_view(), name="list_sala"),
    path('detail/sala/<int:pk>/', views.DetailSala.as_view(), name="detail_sala"),
    path('update/sala/<int:pk>/', views.UpdateSala.as_view(), name="update_sala"),
    path('delete/sala/<int:pk>/', views.DeleteSala.as_view(), name="delete_sala"),

    path('create/oficina/', views.CreateOficina.as_view(), name="create_oficina"),
    path('list/oficina/', views.ListOficina.as_view(), name="list_oficina"),
    path('detail/oficina/<int:pk>/', views.DetailOficina.as_view(), name="detail_oficina"),
    path('update/oficina/<int:pk>/', views.UpdateOficina.as_view(), name="update_oficina"),
    path('delete/oficina/<int:pk>/', views.DeleteOficina.as_view(), name="delete_oficina"),
]

core/models.py
from django.db import models

# Create your models here.

class Recamara(models.Model):
    recamara_name = models.CharField('Nombre:', max_length=50, default="Nombre Mueble Recamara")
    imagen = models.ImageField('Imagen:', upload_to='M-Recamara/', blank=False, null=False, default="/static/images/logos/Logo.png")
    descripcion = models.CharField('Descripcion:', max_length=300, default="Descripcion Mueble Recamara")
    stock = models.IntegerField('Stock:', default=0)
    precio = models.FloatField('Precio:', default=0.00)
    timestamp = models.DateField(auto_now_add=True)
    update_recamara = models.DateField(auto_now=True, auto_now_add=False)
    status = models.BooleanField('Estado:', default=True)
    codigo = models.SlugField('Código:', max_length=16)

    def __str__(self):
        return self.recamara_name

class Bano(models.Model):
    bano_name = models.CharField('Nombre:', max_length=50, default="Nombre Mueble Baño")
    imagen = models.ImageField('Imagen:', upload_to='M-Banos/', blank=False, null=False, default="/static/images/logos/Logo.png")
    descripcion = models.CharField('Descripcion:', max_length=300, default="Descripcion Mueble Baño")
    stock = models.IntegerField('Stock:', default=0)
    precio = models.FloatField('Precio:', default=0.00)
    timestamp = models.DateField(auto_now_add=True)
    update_baño = models.DateField(auto_now=True, auto_now_add=False)
    status = models.BooleanField('Estado:', default=True)
    codigo = models.SlugField('Código:', max_length=16)

    def __str__(self):
        return self.bano_name

class Cocina(models.Model):
    cocina_name = models.CharField('Nombre:', max_length=50, default="Nombre Mueble Cocina")
    imagen = models.ImageField('Imagen:', upload_to='M-Cocinas/', blank=False, null=False, default="/static/images/logos/Logo.png")
    descripcion = models.CharField('Descripcion:', max_length=300, default="Descripcion Mueble Cocina")
    stock = models.IntegerField('Stock:', default=0)
    precio = models.FloatField('Precio:', default=0.00)
    timestamp = models.DateField(auto_now_add=True)
    update_cocina = models.DateField(auto_now=True, auto_now_add=False)
    status = models.BooleanField('Estado:', default=True)
    codigo = models.SlugField('Código:', max_length=16)

    def __str__(self):
        return self.cocina_name

class Comedor(models.Model):
    comedor_name = models.CharField('Nombre:', max_length=50, default="Nombre Mueble Comedor")
    imagen = models.ImageField('Imagen:', upload_to='M-Comedores/', blank=False, null=False, default="/static/images/logos/Logo.png")
    descripcion = models.CharField('Descripcion:', max_length=300, default="Descripcion Mueble Comedor")
    stock = models.IntegerField('Stock:', default=0)
    precio = models.FloatField('Precio:', default=0.00)
    timestamp = models.DateField(auto_now_add=True)
    update_comedor = models.DateField(auto_now=True, auto_now_add=False)
    status = models.BooleanField('Estado:', default=True)
    codigo = models.SlugField('Código:', max_length=16)

    def __str__(self):
        return self.comedor_name

class Sala(models.Model):
    sala_name = models.CharField('Nombre:', max_length=50, default="Nombre Mueble Sala")
    imagen = models.ImageField('Imagen:', upload_to='M-Sala/', blank=False, null=False, default="/static/images/logos/Logo.png")
    descripcion = models.CharField('Descripcion:', max_length=300, default="Descripcion Mueble Sala")
    stock = models.IntegerField('Stock:', default=0)
    precio = models.FloatField('Precio:', default=0.00)
    timestamp = models.DateField(auto_now_add=True)
    update_sala = models.DateField(auto_now=True, auto_now_add=False)
    status = models.BooleanField('Estado:', default=True)
    codigo = models.SlugField('Código:', max_length=16)

    def __str__(self):
        return self.sala_name

class Oficina(models.Model):
    oficina_name = models.CharField('Nombre:', max_length=50, default="Nombre Mueble Oficina")
    imagen = models.ImageField('Imagen:', upload_to='M-Oficinas/', blank=False, null=False, default="/static/images/logos/Logo.png")
    descripcion = models.CharField('Descripcion:', max_length=300, default="Descripcion Mueble Oficina")
    stock = models.IntegerField('Stock:', default=0)
    precio = models.FloatField('Precio:', default=0.00)
    timestamp = models.DateField(auto_now_add=True)
    update_oficina = models.DateField(auto_now=True, auto_now_add=False)
    status = models.BooleanField('Estado:', default=True)
    codigo = models.SlugField('Código:', max_length=16)

    def __str__(self):
        return self.oficina_name

core/views.py
from django.shortcuts import render

from django.views import generic
from django.urls import reverse_lazy

# from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Recamara, Bano, Cocina, Comedor, Sala, Oficina
from .forms import RecamaraForm, UpdateRecamaraForm, BanoForm, UpdateBanoForm, CocinaForm, UpdateCocinaForm, ComedorForm, UpdateComedorForm, SalaForm, UpdateSalaForm, OficinaForm, UpdateOficinaForm

# Create your views here.

#------------------------------------------ CRUD RECAMARA -------------------------------------------#
#List
class ListRecamara(generic.View):
    template_name = "core/recamara/list_recamara.html"
    context = {}
    login_url = reverse_lazy("home:inicio")

    def get(self, request, *args, **kwargs):
        recamaras = Recamara.objects.filter(status=True)
        self.context = {
            "recamaras": recamaras
        }
        return render(request, self.template_name, self.context)

#Detail
class DetailRecamara(generic.View):
    template_name = "core/recamara/detail_recamara.html"
    context = {}
    login_url = reverse_lazy("home:inicio")

    def get(self, request, pk, *args, **kwargs):
        recamara = Recamara.objects.get(pk=pk)
        self.context = {
            "recamara": recamara
        }
        return render(request, self.template_name, self.context)

#Create
class CreateRecamara(generic.CreateView):
    template_name = "core/recamara/create_recamara.html"
    model = Recamara
    form_class = RecamaraForm
    success_url = reverse_lazy("core:list_recamara")
    login_url = reverse_lazy("home:inicio")

#Update
class UpdateRecamara(generic.UpdateView):
    template_name = "core/recamara/update_recamara.html"
    model = Recamara
    form_class = UpdateRecamaraForm
    success_url = reverse_lazy("core:list_recamara")
    login_url = reverse_lazy("home:inicio")

#Delete
class DeleteRecamara(generic.DeleteView):
    template_name = "core/recamara/delete_recamara.html"
    model = Recamara
    success_url = reverse_lazy("core:list_recamara")
    login_url = reverse_lazy("home:inicio")

#------------------------------------------ CRUD BATHROOM -------------------------------------------#
#List
class ListBano(generic.View):
    template_name = "core/bano/list_bano.html"
    login_url = reverse_lazy("home:inicio")

    def get(self, request, *args, **kwargs):
        banos = Bano.objects.filter(status=True)
        return render(request, self.template_name, {'banos': banos})

#Detail
class DetailBano(generic.View):
    template_name = "core/bano/detail_bano.html"
    context = {}
    login_url = reverse_lazy("home:inicio")

    def get(self, request, pk, *args, **kwargs):
        bano = Bano.objects.get(pk=pk)
        self.context = {
            "bano": bano
        }
        return render(request, self.template_name, self.context)

#Create
class CreateBano(generic.CreateView):
    template_name = "core/bano/create_bano.html"
    model = Bano
    form_class = BanoForm
    success_url = reverse_lazy("core:list_bano")
    login_url = reverse_lazy("home:inicio")

#Update
class UpdateBano(generic.UpdateView):
    template_name = "core/bano/update_bano.html"
    model = Bano
    form_class = UpdateBanoForm
    success_url = reverse_lazy("core:list_bano")
    login_url = reverse_lazy("home:inicio")

#Delete
class DeleteBano(generic.DeleteView):
    template_name = "core/bano/delete_bano.html"
    model = Bano
    success_url = reverse_lazy("core:list_bano")
    login_url = reverse_lazy("home:inicio")

#------------------------------------------ CRUD COCINA -------------------------------------------#
#List
class ListCocina(generic.View):
    template_name = "core/cocina/list_cocina.html"
    context = {}
    login_url = reverse_lazy("home:inicio")

    def get(self, request, *args, **kwargs):
        cocinas = Cocina.objects.filter(status=True)
        self.context = {
            "cocinas": cocinas
        }
        return render(request, self.template_name, self.context)

#Detail
class DetailCocina(generic.View):
    template_name = "core/cocina/detail_cocina.html"
    context = {}
    login_url = reverse_lazy("home:inicio")

    def get(self, request, pk, *args, **kwargs):
        cocina = Cocina.objects.get(pk=pk)
        self.context = {
            "cocina": cocina
        }
        return render(request, self.template_name, self.context)

#Create
class CreateCocina(generic.CreateView):
    template_name = "core/cocina/create_cocina.html"
    model = Cocina
    form_class = CocinaForm
    success_url = reverse_lazy("core:list_cocina")
    login_url = reverse_lazy("home:inicio")

#Update
class UpdateCocina(generic.UpdateView):
    template_name = "core/cocina/update_cocina.html"
    model = Cocina
    form_class = UpdateCocinaForm
    success_url = reverse_lazy("core:list_cocina")
    login_url = reverse_lazy("home:inicio")

#Delete
class DeleteCocina(generic.DeleteView):
    template_name = "core/cocina/delete_cocina.html"
    model = Cocina
    success_url = reverse_lazy("core:list_cocina")
    login_url = reverse_lazy("home:inicio")

#------------------------------------------ CRUD COMEDOR -------------------------------------------#
#List
class ListComedor(generic.View):
    template_name = "core/comedor/list_comedor.html"
    context = {}
    login_url = reverse_lazy("home:inicio")

    def get(self, request, *args, **kwargs):
        comedores = Comedor.objects.filter(status=True)
        self.context = {
            "comedores": comedores
        }
        return render(request, self.template_name, self.context)

#Detail
class DetailComedor(generic.View):
    template_name = "core/comedor/detail_comedor.html"
    context = {}
    login_url = reverse_lazy("home:inicio")

    def get(self, request, pk, *args, **kwargs):
        comedor = Comedor.objects.get(pk=pk)
        self.context = {
            "comedor": comedor
        }
        return render(request, self.template_name, self.context)

#Create
class CreateComedor(generic.CreateView):
    template_name = "core/comedor/create_comedor.html"
    model = Comedor
    form_class = ComedorForm
    success_url = reverse_lazy("core:list_comedor")
    login_url = reverse_lazy("home:inicio")

#Update
class UpdateComedor(generic.UpdateView):
    template_name = "core/comedor/update_comedor.html"
    model = Comedor
    form_class = UpdateComedorForm
    success_url = reverse_lazy("core:list_comedor")
    login_url = reverse_lazy("home:inicio")

#Delete
class DeleteComedor(generic.DeleteView):
    template_name = "core/comedor/delete_comedor.html"
    model = Comedor
    success_url = reverse_lazy("core:list_comedor")
    login_url = reverse_lazy("home:inicio")

#------------------------------------------ CRUD SALA -------------------------------------------#
#List
class ListSala(generic.View):
    template_name = "core/sala/list_sala.html"
    context = {}
    login_url = reverse_lazy("home:inicio")

    def get(self, request, *args, **kwargs):
        salas = Sala.objects.filter(status=True)
        self.context = {
            "salas": salas
        }
        return render(request, self.template_name, self.context)

#Detail
class DetailSala(generic.View):
    template_name = "core/sala/detail_sala.html"
    context = {}
    login_url = reverse_lazy("home:inicio")

    def get(self, request, pk, *args, **kwargs):
        sala = Sala.objects.get(pk=pk)
        self.context = {
            "sala": sala
        }
        return render(request, self.template_name, self.context)

#Create
class CreateSala(generic.CreateView):
    template_name = "core/sala/create_sala.html"
    model = Sala
    form_class = SalaForm
    success_url = reverse_lazy("core:list_sala")
    login_url = reverse_lazy("home:inicio")

#Update
class UpdateSala(generic.UpdateView):
    template_name = "core/sala/update_sala.html"
    model = Sala
    form_class = UpdateSalaForm
    success_url = reverse_lazy("core:list_sala")
    login_url = reverse_lazy("home:inicio")

#Delete
class DeleteSala(generic.DeleteView):
    template_name = "core/sala/delete_sala.html"
    model = Sala
    success_url = reverse_lazy("core:list_sala")
    login_url = reverse_lazy("home:inicio")

#------------------------------------------ CRUD OFICINA -------------------------------------------#
#List
class ListOficina(generic.View):
    template_name = "core/oficina/list_oficina.html"
    context = {}
    login_url = reverse_lazy("home:inicio")

    def get(self, request, *args, **kwargs):
        oficinas = Oficina.objects.filter(status=True)
        self.context = {
            "oficinas": oficinas
        }
        return render(request, self.template_name, self.context)

#Detail
class DetailOficina(generic.View):
    template_name = "core/oficina/detail_oficina.html"
    context = {}
    login_url = reverse_lazy("home:inicio")

    def get(self, request, pk, *args, **kwargs):
        oficina = Oficina.objects.get(pk=pk)
        self.context = {
            "oficina": oficina
        }
        return render(request, self.template_name, self.context)

#Create
class CreateOficina(generic.CreateView):
    template_name = "core/oficina/create_oficina.html"
    model = Oficina
    form_class = OficinaForm
    success_url = reverse_lazy("core:list_oficina")
    login_url = reverse_lazy("home:inicio")

#Update
class UpdateOficina(generic.UpdateView):
    template_name = "core/oficina/update_oficina.html"
    model = Oficina
    form_class = UpdateOficinaForm
    success_url = reverse_lazy("core:list_oficina")
    login_url = reverse_lazy("home:inicio")

#Delete
class DeleteOficina(generic.DeleteView):
    template_name = "core/oficina/delete_oficina.html"
    model = Oficina
    success_url = reverse_lazy("core:list_oficina")
    login_url = reverse_lazy("home:inicio")

templates/core/oficina/create_oficina.html
{% extends "base/base.html" %}

{% block title %} CREATE OFICINA VIEW {% endblock title %}

{% block content %}
    <div class="container text-center">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <form action="" method="post" class="form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    <br>
                    <button type="submit" class="btn btn-outline-success" style="border-radius: 10px; margin-right: 40px;">Create</button>
                    <a href="{% url 'core:list_oficina' %}" class="btn btn-outline-danger" style="border-radius: 10px;">Cancel</a>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/core/oficina/delete_oficina.html
{% extends "base/base.html" %}

{% block title %}
    DELETE OFICINA VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="card border-danger mb-3" style="max-width: 20rem;">
            <div class="card-header">Delete</div>
            <div class="card-body">
              <h4 class="card-title">{{ object.oficina_name }}</h4>
              <p><h1>¿Realmente deseas eliminar esto?</h1></p>
              <button type="submit" class="btn btn-danger">Delete</button>
              <a href="{% url 'core:list_oficina' %}" class="btn btn-warning">Cancel</a>
            </div>
          </div>
    </form>
{% endblock content %}

templates/core/oficina/detail_oficina.html
{% extends "base/base.html" %}

{% block title %}
    DETAIL OFICINA VIEW
{% endblock title %}

{% block content %}
<br><br>
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ oficina.oficina_name }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>Descripcion: </strong> {{ oficina.descripcion }} <br>
          <strong>Stock: </strong> {{ oficina.stock }} <br>
          <strong>Precio: </strong>$ {{ oficina.precio }} <br>
          <br><br>
          <strong>Estado: </strong> {{ oficina.status }}
        </div>
      </div>
    </div>
  </div>
  <br>
  <a href="{% url 'core:list_oficina' %}" class="btn btn-outline-warning" style="border-radius: 10px;">Back To List</a>
{% endblock content %}

templates/core/oficina/list_oficina.html
{% extends "base/base.html" %}

{% block title %} LIST OFICINA VIEW {% endblock title %}

{% block content %}
<br>
{% if request.user.is_staff or request.user.is_superuser %}
<a href="{% url 'core:create_oficina' %}" class="btn btn-outline-success form-control" style="border-radius: 10px;">Create</a>
    <br><br>
        <table class="table table-striped table-hover">
            <thead class="table-primary">
                <th>ID</th>
                <th>NOMBRE OFICINA</th>
                <th>IMAGEN</th>
                <th>DESCRIPCION</th>
                <th>PRECIO</th>
                <th>STOCK</th>
                <th>ESTADO</th>
                <th></th>
                <th>ACTIONS</th>
                <th></th>
            </thead>
            <tbody>
                {% for oficina in oficinas %}
                    <tr>
                        <td>{{ oficina.id }}</td>
                        <td>{{ oficina.oficina_name }}</td>
                        <td>{{ oficina.imagen }}</td>
                        <td>{{ oficina.descripcion }}</td>
                        <td>{{ oficina.precio }}</td>
                        <td>{{ oficina.stock }}</td>
                        <td>{{ oficina.status }}</td>
                        <td><a href="{% url 'core:detail_oficina' oficina.id %}" class="btn btn-outline-info" style="border-radius: 10px;">Detail</a></td>
                        <td><a href="{% url 'core:update_oficina' oficina.id %}" class="btn btn-outline-warning" style="border-radius: 10px;">Update</a></td>
                        <td><a href="{% url 'core:delete_oficina' oficina.id %}" class="btn btn-outline-danger" style="border-radius: 10px;">Delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
    <br>
<table>
    {% for oficina in oficinas %}
        <td style="padding: 20px;">
            <div class="card" style="width: 25rem;">
                <div class="card-body">
                    <p><img src="/media/{{ oficina.imagen }}" class="card-img-top" alt="imagen"></p>
                    <h5 class="card-title"> {{ oficina.oficina_name }} </h5>
                        <p style="text-align: center;" >$ {{ oficina.precio}} </p>
                    <p class="card-text" style="text-align: center;">{{ oficina.descripcion }} </p>
                </div>
            </div>
        </td>
        {% if forloop.counter|divisibleby:4 %}
            </tr><tr> <!-- Salto de línea cada cuatro iteraciones -->
        {% endif %}
    {% endfor %}
</table>
{% endblock content %}

templates/core/oficina/update_oficina.html
{% extends "base/base.html" %}

{% block title %}
    UPDATE OFICINA VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary form-control">Update</button>
        <br>
        <a href="{% url 'core:list_oficina' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}